fixed pre-commit hook

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,14 @@
 #!/bin/bash
 #
 # An example hook script to verify what is about to be committed.
-# Called by "git commit" with no arguments.  The hook shou	ld
+# Called by "git commit" with no arguments.  The hook should
 # exit with non-zero status after issuing an appropriate message if
 # it wants to stop the commit.
 #
-# To enable this hook, rename this file to "pre-commit".		
+# To enable this hook, rename this file to "pre-commit".
+
+
+
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
 	against=HEAD
@@ -42,6 +45,33 @@ If you know what you are doing you can disable this check using:
   git config hooks.allownonascii true
 EOF
 	exit 1
+fi
+# https://stackoverflow.com/questions/22866609/can-clang-format-tell-me-if-formatting-changes-are-necessary
+dir_list="$PWD"  # Add the directories you want here
+cmd="git diff --staged -- '***.c' '***.h' '***.cpp' '***.hpp' -U0 --no-color --staged HEAD -- $dir_list | clang-format-diff -p1"
+
+echo ""
+echo "Running clang-format on this commit"
+echo ""
+
+# Execute the format command
+diff=$(eval "$cmd")
+if [[ $? -ne 0 ]]
+then
+    echo "Command failed to execute."
+    exit 1
+fi
+
+# Print the outcome
+if [[ -z "$diff" ]]	
+then
+    echo "Everything is clean"
+    exit 0
+else
+    echo "$diff"
+    echo "Commit aborted due to code format inconsistencies."
+    git reset --  '***.c' '***.h' '***.cpp' '***.hpp'
+    exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
